name: Build macOS

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.0.0)'
        required: true

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: npm ci
    - name: Build macOS
      run: npm run build:mac
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./dist/*.dmg
          ./dist/*.zip
        tag_name: ${{ github.event.inputs.release_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}