name: Build Linux

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: npm ci
    - name: Build Linux
      run: npm run build:linux
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/*.AppImage
          ./dist/*.deb
          ./dist/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}